/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as uniswapExampleSol from "./UniswapExample.sol";
export { IUniversalRouter__factory } from "./IUniversalRouter__factory";
