/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapExampleSol from "./UniswapExample.sol";
export type { uniswapExampleSol };
export type { IUniversalRouter } from "./IUniversalRouter";
